// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  jNet.particles = function(selector) {
    this.canvas = jNet(selector);
  };

}).call(this);

//# sourceMappingURL=particles.js.map
